///////////////////////////////////////////////////////////
//  Avatar.as
//  Macromedia ActionScript Implementation of the Class Avatar
//  Generated by Enterprise Architect
//  Created on:      25-二月-2016 18:53:08
//  Original author: Administrator
///////////////////////////////////////////////////////////

package src.map
{

	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 25-二月-2016 18:53:08
	 */
	public class Avatar extends Sprite
	{
	    protected var _name: String;
	    protected var _sceneX: int;
	    protected var _sceneY: int;
	    /**
	     * 记录显示对象的状态
	     */
	    protected var _state: String;
	    private var m_hello;

	    public function Avatar()
	    {
	    }

		public function get hello(): String
		{
		}

	}//end Avatar

}