///////////////////////////////////////////////////////////
//  NPC.as
//  Macromedia ActionScript Implementation of the Class NPC
//  Generated by Enterprise Architect
//  Created on:      25-二月-2016 18:53:08
//  Original author: Administrator
///////////////////////////////////////////////////////////

package src.map
{
	import src.map.Avatar;

	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 25-二月-2016 18:53:08
	 */
	public class NPC extends Avatar
	{
	    private var _name: String;
	    private var _sceneX: int;
	    private var _sceneY: String;
	    private var _state: String;
	    public var isTalking: Boolean;

	    public function NPC()
	    {
	    }

	    public function openTalkView(): void
	    {
	    }

	}//end NPC

}