///////////////////////////////////////////////////////////
//  Player.as
//  Macromedia ActionScript Implementation of the Class Player
//  Generated by Enterprise Architect
//  Created on:      25-二月-2016 18:53:08
//  Original author: Administrator
///////////////////////////////////////////////////////////

package src.map
{
	import src.map.Avatar;

	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 25-二月-2016 18:53:08
	 */
	public class Player extends Avatar
	{
	    private var _isMoving: Boolean;
	    private var _name: String;
	    private var _sceneX: int;
	    private var _sceneY: int;
	    private var _state: String;

	    /**
	     * 
	     * @param x
	     * @param y    y
	     */
	    public function mouseClickhandler(x:int, y:int): void
	    {
	    }

	    public function move(): void
	    {
	    }

	    public function Player()
	    {
	    }

	}//end Player

}