///////////////////////////////////////////////////////////
//  Portal.as
//  Macromedia ActionScript Implementation of the Class Portal
//  Generated by Enterprise Architect
//  Created on:      25-二月-2016 18:53:08
//  Original author: Administrator
///////////////////////////////////////////////////////////

package src.map
{
	import src.map.Avatar;

	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 25-二月-2016 18:53:08
	 */
	public class Portal extends Avatar
	{
	    private var _name: String;
	    private var _sceneX: int;
	    private var _sceneY: int;

	    static public function get name(): String
	    {
	    	return _name;
	    }

	    /**
		 * 
		 * @param str
		 */
	    static public function set name(str:String): void
	    {
	    	_name = str;
	    }

	    public function Portal()
	    {
	    }



		public function get sceneY(): int
		{
		}

		private function hello():void
		{
			
		}
		/**
		 * 
		 * @param str
		 */
		static public function set sceneY(str:String): void
		{
			_name = newVal;
		}

	}//end Portal

}