///////////////////////////////////////////////////////////
//  Scene.as
//  Macromedia ActionScript Implementation of the Class Scene
//  Generated by Enterprise Architect
//  Created on:      26-二月-2016 12:31:47
//  Original author: Administrator
///////////////////////////////////////////////////////////

package src.map
{
	import src.map.Sprite;
	import src.map.Player;

	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 26-二月-2016 12:31:47
	 */
	public class Scene
	{
	    private var _name: String;
	    private var _npcLayer: Sprite;
	    private var _npcList: Array;
	    private var _player: Player;
	    private var _playLayer: Sprite;
	    private var _portalList: Array;
	    private var _sceneId: int;
	    private var _sceneLayer: Sprite;

	    /**
	     * 
	     * @param type    type
	     */
	    public function addDisplay(type:String): void
	    {
	    }

	    /**
	     * 
	     * @param id    id
	     */
	    public function changeScene(id:int): void
	    {
	    }

	    /**
	     * 
	     * @param e    e
	     */
	    private function mouseDownHanler(e:MouseEvent): void
	    {
	    }

	    /**
	     * 
	     * @param e    e
	     */
	    private function mouseUpHanler(e:MouseEvent): void
	    {
	    }

	    public function Scene()
	    {
	    }

	    /**
	     * 
	     * @param isshow    isshow
	     */
	    public function showDisplay(isshow:Boolean): void
	    {
	    }

	}//end Scene

}