///////////////////////////////////////////////////////////
//  Sprite.as
//  Macromedia ActionScript Implementation of the Class Sprite
//  Generated by Enterprise Architect
//  Created on:      25-二月-2016 18:53:08
//  Original author: Administrator
///////////////////////////////////////////////////////////

package src.map
{
	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 25-二月-2016 18:53:08
	 */
	public class Sprite
	{
	    public function Sprite()
	    {
	    }

	}//end Sprite

}